name: detection
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py37h06a4308_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h7b6447c_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openssl=1.1.1s=h7f8727e_0
  - pillow=9.2.0=py37hace64e9_1
  - pip=22.2.2=py37h06a4308_0
  - python=3.7.15=haa1d7c7_0
  - pytorch=1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.7.2=py37
  - torchvision=0.8.2=py37_cu110
  - typing_extensions=4.3.0=py37h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.3.0
    - addict==2.4.0
    - albumentations==0.4.6
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - black==21.4b2
    - bleach==5.0.1
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - colorama==0.4.6
    - commonmark==0.9.1
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - future==0.18.2
    - fvcore==0.1.5.post20220512
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - hydra-core==1.2.0
    - idna==3.4
    - imageio==2.22.4
    - imgaug==0.4.0
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - iopath==0.1.9
    - ipykernel==6.16.2
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jsonschema==4.17.0
    - jupyter==1.0.0
    - jupyter-client==7.4.5
    - jupyter-console==6.4.4
    - jupyter-core==4.11.2
    - jupyter-server==1.23.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - map-boxes==1.0.5
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mmcv-full==1.7.0
    - model-index==0.1.11
    - mypy-extensions==0.4.3
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.4
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.6.3
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - oauthlib==3.2.2
    - omegaconf==2.2.3
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - openmim==0.3.3
    - ordered-set==4.1.0
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.10.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - portalocker==2.6.0
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.32
    - protobuf==3.20.3
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pycparser==2.21
    - pydot==1.4.2
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - qudida==0.0.4
    - regex==2022.10.31
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==12.6.0
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.1
    - send2trash==1.8.0
    - sentry-sdk==1.11.0
    - setproctitle==1.3.2
    - shapely==1.8.5.post1
    - shortuuid==1.0.11
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - tabulate==0.9.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.1.0
    - terminado==0.17.0
    - terminaltables==3.1.10
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tinycss2==1.2.1
    - toml==0.10.2
    - torchnet==0.0.4
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typed-ast==1.5.4
    - urllib3==1.26.12
    - visdom==0.2.3
    - wandb==0.13.5
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - yacs==0.1.8
    - yapf==0.32.0
    - zipp==3.10.0
prefix: /opt/conda/envs/detection
